name: Get Flag from AWS

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  get-flag:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::841551936969:role/sts-lab-2-target
          aws-region: us-east-1

      - name: Get Secret (flag)
        run: |
          aws secretsmanager get-secret-value \
            --secret-id flag_sts_lab_2 \
            --region us-east-1